/* Get committee venues */
CREATE OR REPLACE FUNCTION FN_GET_COMMITTEE_VENUES (
    p_user_id       IN  NUMBER
)
RETURN SYS_REFCURSOR
IS
    v_committee_id ORGANIZING_COMMITTEE.COMMITTEE_ID%TYPE;
    v_cursor SYS_REFCURSOR;
BEGIN
    SELECT COMMITTEE_ID INTO v_committee_id
    FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'ORGANIZING_COMMITTEE';

    OPEN v_cursor FOR
        SELECT VENUE_ID, VENUE_NAME, ADDRESS, CAPACITY, STATUS
        FROM VENUE
        WHERE COMMITTEE_ID = v_committee_id
        ORDER BY VENUE_NAME;
    RETURN v_cursor;
END FN_GET_COMMITTEE_VENUES;
/
