/* Get all users for administration */
CREATE OR REPLACE FUNCTION FN_GET_ALL_USERS
RETURN SYS_REFCURSOR
IS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT u.USER_ID, u.EMAIL, r.ROLE_CODE AS ROLE, u.ACCOUNT_STATUS AS STATUS,
               u.CREATED_AT, u.LAST_LOGIN_AT AS LAST_LOGIN
        FROM APP_USER u
        JOIN USER_ROLE_LINK r ON u.USER_ID = r.USER_ID
        ORDER BY u.CREATED_AT DESC;
    RETURN v_cursor;
END FN_GET_ALL_USERS;
/
