
CREATE OR REPLACE FUNCTION FN_GET_PUBLIC_STATS
RETURN SYS_REFCURSOR
AS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
        SELECT
            (SELECT COUNT(*) FROM DONOR WHERE STATUS = 'ACTIVE') AS TOTAL_DONORS,
            (SELECT COUNT(*) FROM DONATION_CAMP WHERE STATUS IN ('PUBLISHED', 'ONGOING')) AS ACTIVE_CAMPS,
            (SELECT NVL(SUM(UNITS_COLLECTED), 0) FROM DONATION_RECORD WHERE STATUS = 'SUBMITTED') AS TOTAL_UNITS
        FROM DUAL;
    RETURN v_cursor;
END FN_GET_PUBLIC_STATS;
/

/* Get camps by a comma-separated list of IDs */
CREATE OR REPLACE PROCEDURE GET_CAMPS_BY_IDS (
    p_camp_ids      IN  VARCHAR2,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_sql VARCHAR2(4000);
BEGIN
    v_sql := 'SELECT CAMP_ID, COMMITTEE_ID, VENUE_ID, CAMP_TITLE, CAMP_DESCRIPTION, ' ||
             'CAMP_DATE, START_TIME, END_TIME, CAPACITY, STATUS, PUBLIC_VISIBLE ' ||
             'FROM DONATION_CAMP ' ||
             'WHERE CAMP_ID IN (' || p_camp_ids || ')';

    OPEN p_result_cursor FOR v_sql;
END GET_CAMPS_BY_IDS;
/

/* Check if a camp is publicly visible */
CREATE OR REPLACE FUNCTION IS_PUBLICLY_VISIBLE (
    p_camp_id IN NUMBER
)
RETURN NUMBER
IS
    v_status VARCHAR2(20);
    v_public_visible CHAR(1);
BEGIN
    SELECT status, public_visible 
    INTO v_status, v_public_visible
    FROM donation_camp
    WHERE camp_id = p_camp_id;

    IF v_public_visible = 'Y' AND v_status IN ('PUBLISHED', 'ONGOING', 'COMPLETED') THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END IS_PUBLICLY_VISIBLE;
/

/* Get all active blood banks */
CREATE OR REPLACE FUNCTION FN_GET_ACTIVE_BLOOD_BANKS
RETURN SYS_REFCURSOR
IS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
    SELECT BLOOD_BANK_ID, BANK_NAME, ADDRESS AS DISTRICT
    FROM BLOOD_BANK
    WHERE STATUS = 'ACTIVE'
    ORDER BY BANK_NAME;
    RETURN v_cursor;
END FN_GET_ACTIVE_BLOOD_BANKS;
/
