CREATE OR REPLACE PROCEDURE SUBMIT_MEDICAL_CHECK(
    p_user_id IN NUMBER,
    p_status IN VARCHAR2
) AS
BEGIN
    UPDATE DONOR
    SET MEDICAL_CHECK_STATUS = p_status,
        LAST_MEDICAL_CHECK_AT = CURRENT_TIMESTAMP
    WHERE USER_ID = p_user_id;
    COMMIT;
END SUBMIT_MEDICAL_CHECK;
/
