/* Get System Audit Logs */
CREATE OR REPLACE FUNCTION FN_GET_SYSTEM_AUDIT_LOGS
RETURN SYS_REFCURSOR
IS
    v_cursor SYS_REFCURSOR;
BEGIN
    OPEN v_cursor FOR
    SELECT * FROM (
        SELECT AUDIT_ID, ACTOR_ROLE_CODE, ACTOR_USER_ID, ACTION_CODE, ENTITY_TYPE, ENTITY_ID, DETAILS, CREATED_AT
        FROM AUDIT_LOG
        ORDER BY CREATED_AT DESC
    ) WHERE ROWNUM <= 200;
    RETURN v_cursor;
END;
/
