ALTER SESSION SET CONTAINER = LifeLineConnect_PDB;

GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO LLC_ADMIN;
GRANT DBA TO LLC_ADMIN;
ALTER PLUGGABLE DATABASE LifeLineConnect_PDB OPEN;
ALTER PLUGGABLE DATABASE ALL SAVE STATE;
