-- ================================================================
-- Blood Bank Procedures
-- ================================================================

CREATE OR REPLACE PROCEDURE GET_BANK_DASHBOARD(
    p_user_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_bank_id NUMBER;
BEGIN
    SELECT BLOOD_BANK_ID INTO v_bank_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'BLOOD_BANK';
    
    OPEN p_result_cursor FOR
    SELECT 
        (SELECT COUNT(*) FROM BLOOD_UNIT WHERE BLOOD_BANK_ID = v_bank_id AND STATUS = 'AVAILABLE') AS TOTAL_UNITS,
        (SELECT COUNT(*) FROM DONATION_TRANSFER WHERE BLOOD_BANK_ID = v_bank_id AND STATUS IN ('DISPATCHED', 'IN_TRANSIT')) AS INCOMING_TRANSFERS,
        (SELECT COUNT(*) FROM HOSPITAL_BLOOD_REQUEST WHERE BLOOD_BANK_ID = v_bank_id AND STATUS = 'PENDING') AS PENDING_REQUESTS,
        (SELECT COUNT(*) FROM BLOOD_UNIT WHERE BLOOD_BANK_ID = v_bank_id AND STATUS = 'AVAILABLE' AND EXPIRY_DATE < SYSDATE + 7) AS EXPIRING_SOON
    FROM DUAL;
END GET_BANK_DASHBOARD;
/

CREATE OR REPLACE PROCEDURE GET_BANK_INVENTORY(
    p_user_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_bank_id NUMBER;
BEGIN
    SELECT BLOOD_BANK_ID INTO v_bank_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'BLOOD_BANK';
    
    -- Auto-expire any units past expiry date
    UPDATE BLOOD_UNIT
    SET STATUS = 'EXPIRED', UPDATED_AT = SYSTIMESTAMP
    WHERE BLOOD_BANK_ID = v_bank_id AND STATUS = 'AVAILABLE' AND EXPIRY_DATE < TRUNC(SYSDATE);
    
    COMMIT;
    
    OPEN p_result_cursor FOR
    SELECT BLOOD_UNIT_ID, UNIT_CODE, BLOOD_GROUP, COLLECTION_DATE, EXPIRY_DATE, STATUS, STORAGE_LOCATION
    FROM BLOOD_UNIT
    WHERE BLOOD_BANK_ID = v_bank_id
    ORDER BY EXPIRY_DATE ASC;
END GET_BANK_INVENTORY;
/

CREATE OR REPLACE PROCEDURE GET_BANK_TRANSFERS(
    p_user_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_bank_id NUMBER;
BEGIN
    SELECT BLOOD_BANK_ID INTO v_bank_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'BLOOD_BANK';
    
    OPEN p_result_cursor FOR
    SELECT t.TRANSFER_ID, t.TRANSFER_CODE, t.STATUS, t.CREATED_AT, t.DISPATCHED_AT, t.RECEIVED_AT, t.RECEIVED_UNIT_COUNT,
           c.CAMP_TITLE, org.COMMITTEE_NAME
    FROM DONATION_TRANSFER t
    JOIN DONATION_CAMP c ON t.CAMP_ID = c.CAMP_ID
    JOIN ORGANIZING_COMMITTEE org ON t.COMMITTEE_ID = org.COMMITTEE_ID
    WHERE t.BLOOD_BANK_ID = v_bank_id
    ORDER BY t.CREATED_AT DESC;
END GET_BANK_TRANSFERS;
/

CREATE OR REPLACE PROCEDURE RECEIVE_TRANSFER(
    p_user_id IN NUMBER,
    p_transfer_id IN NUMBER
) AS
    v_bank_id NUMBER;
    v_status VARCHAR2(20);
    v_count NUMBER := 0;
    
    CURSOR c_items IS
        SELECT ti.DONATION_ID, dr.BLOOD_GROUP, dr.DONATION_DATE
        FROM DONATION_TRANSFER_ITEM ti
        JOIN DONATION_RECORD dr ON ti.DONATION_ID = dr.DONATION_ID
        WHERE ti.TRANSFER_ID = p_transfer_id;
BEGIN
    SELECT BLOOD_BANK_ID INTO v_bank_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'BLOOD_BANK';
    
    SELECT STATUS INTO v_status FROM DONATION_TRANSFER 
    WHERE TRANSFER_ID = p_transfer_id AND BLOOD_BANK_ID = v_bank_id;
    
    IF v_status = 'RECEIVED' THEN
        RETURN;
    END IF;
    
    -- Loop through items and generate blood units
    FOR item IN c_items LOOP
        INSERT INTO BLOOD_UNIT (
            BLOOD_BANK_ID, DONATION_ID, TRANSFER_ID, UNIT_CODE, BLOOD_GROUP, 
            COLLECTION_DATE, RECEIVED_DATE, EXPIRY_DATE, STATUS, STORAGE_LOCATION
        ) VALUES (
            v_bank_id, item.DONATION_ID, p_transfer_id, 
            'UNIT-' || p_transfer_id || '-' || item.DONATION_ID, 
            item.BLOOD_GROUP, item.DONATION_DATE, SYSDATE, 
            item.DONATION_DATE + 42, -- Blood expires 42 days after collection
            'AVAILABLE', 'Main Storage'
        );
        v_count := v_count + 1;
    END LOOP;
    
    UPDATE DONATION_TRANSFER
    SET STATUS = 'RECEIVED', 
        RECEIVED_AT = SYSTIMESTAMP,
        RECEIVED_UNIT_COUNT = v_count
    WHERE TRANSFER_ID = p_transfer_id;
    
    COMMIT;
END RECEIVE_TRANSFER;
/

CREATE OR REPLACE PROCEDURE GET_BANK_HOSPITAL_REQUESTS(
    p_user_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_bank_id NUMBER;
BEGIN
    SELECT BLOOD_BANK_ID INTO v_bank_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'BLOOD_BANK';
    
    OPEN p_result_cursor FOR
    SELECT r.REQUEST_ID, r.REQUEST_CODE, h.HOSPITAL_NAME, r.BLOOD_GROUP, 
           r.UNITS_REQUIRED, r.UNITS_ALLOCATED, r.UNITS_FULFILLED, 
           r.NEEDED_BY, r.PRIORITY, r.STATUS
    FROM HOSPITAL_BLOOD_REQUEST r
    JOIN HOSPITAL h ON r.HOSPITAL_ID = h.HOSPITAL_ID
    WHERE r.BLOOD_BANK_ID = v_bank_id
    ORDER BY r.NEEDED_BY ASC;
END GET_BANK_HOSPITAL_REQUESTS;
/

CREATE OR REPLACE PROCEDURE GET_BANK_STAFF(
    p_user_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_bank_id NUMBER;
BEGIN
    SELECT BLOOD_BANK_ID INTO v_bank_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'BLOOD_BANK';
    
    OPEN p_result_cursor FOR
    SELECT s.STAFF_ID, s.FULL_NAME, s.POSITION_TITLE, s.PHONE, s.EMAIL, a.ASSIGNED_FROM, a.STATUS
    FROM BANK_STAFF_ASSIGNMENT a
    JOIN STAFF_MEMBER s ON a.STAFF_ID = s.STAFF_ID
    WHERE a.BLOOD_BANK_ID = v_bank_id;
END GET_BANK_STAFF;
/
