-- ================================================================
-- Committee Procedures
-- ================================================================

CREATE OR REPLACE PROCEDURE GET_COMMITTEE_DASHBOARD(
    p_user_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_committee_id NUMBER;
BEGIN
    SELECT COMMITTEE_ID INTO v_committee_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'ORGANIZING_COMMITTEE';
    
    OPEN p_result_cursor FOR
    SELECT 
        (SELECT COUNT(*) FROM DONATION_CAMP WHERE COMMITTEE_ID = v_committee_id AND STATUS IN ('PUBLISHED', 'ONGOING')) AS ACTIVE_CAMPS,
        (SELECT COUNT(*) FROM DONATION_TRANSFER WHERE COMMITTEE_ID = v_committee_id AND STATUS = 'DISPATCHED') AS PENDING_TRANSFERS,
        (SELECT COUNT(*) FROM CAMP_REGISTRATION r JOIN DONATION_CAMP c ON r.CAMP_ID = c.CAMP_ID WHERE c.COMMITTEE_ID = v_committee_id) AS TOTAL_REGISTRATIONS,
        (SELECT COUNT(*) FROM VENUE WHERE COMMITTEE_ID = v_committee_id AND STATUS = 'ACTIVE') AS ACTIVE_VENUES
    FROM DUAL;
END GET_COMMITTEE_DASHBOARD;
/

CREATE OR REPLACE PROCEDURE GET_COMMITTEE_VENUES(
    p_user_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_committee_id NUMBER;
BEGIN
    SELECT COMMITTEE_ID INTO v_committee_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'ORGANIZING_COMMITTEE';
    
    OPEN p_result_cursor FOR
    SELECT VENUE_ID, VENUE_NAME, ADDRESS, CAPACITY, STATUS
    FROM VENUE
    WHERE COMMITTEE_ID = v_committee_id
    ORDER BY VENUE_NAME ASC;
END GET_COMMITTEE_VENUES;
/

CREATE OR REPLACE PROCEDURE GET_COMMITTEE_CAMPS(
    p_user_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_committee_id NUMBER;
BEGIN
    SELECT COMMITTEE_ID INTO v_committee_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'ORGANIZING_COMMITTEE';
    
    OPEN p_result_cursor FOR
    SELECT c.CAMP_ID, c.CAMP_TITLE, c.CAMP_DATE, c.START_TIME, c.END_TIME, c.CAPACITY, c.STATUS, c.PUBLIC_VISIBLE, v.VENUE_NAME
    FROM DONATION_CAMP c
    JOIN VENUE v ON c.VENUE_ID = v.VENUE_ID
    WHERE c.COMMITTEE_ID = v_committee_id
    ORDER BY c.CAMP_DATE DESC;
END GET_COMMITTEE_CAMPS;
/

CREATE OR REPLACE PROCEDURE CREATE_DONATION_CAMP(
    p_user_id IN NUMBER,
    p_venue_id IN NUMBER,
    p_title IN VARCHAR2,
    p_date IN DATE,
    p_start IN TIMESTAMP,
    p_end IN TIMESTAMP,
    p_capacity IN NUMBER,
    p_camp_id OUT NUMBER
) AS
    v_committee_id NUMBER;
BEGIN
    SELECT COMMITTEE_ID INTO v_committee_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'ORGANIZING_COMMITTEE';
    
    INSERT INTO DONATION_CAMP (COMMITTEE_ID, VENUE_ID, CAMP_TITLE, CAMP_DATE, START_TIME, END_TIME, CAPACITY, STATUS, PUBLIC_VISIBLE)
    VALUES (v_committee_id, p_venue_id, p_title, p_date, p_start, p_end, p_capacity, 'PUBLISHED', 'Y')
    RETURNING CAMP_ID INTO p_camp_id;
    
    COMMIT;
END CREATE_DONATION_CAMP;
/

CREATE OR REPLACE PROCEDURE GET_CAMP_ATTENDANCE(
    p_user_id IN NUMBER,
    p_camp_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_committee_id NUMBER;
    v_camp_exists NUMBER;
BEGIN
    SELECT COMMITTEE_ID INTO v_committee_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'ORGANIZING_COMMITTEE';
    
    -- Verify camp belongs to committee
    SELECT COUNT(*) INTO v_camp_exists FROM DONATION_CAMP WHERE CAMP_ID = p_camp_id AND COMMITTEE_ID = v_committee_id;
    IF v_camp_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Unauthorized camp access');
    END IF;
    
    OPEN p_result_cursor FOR
    SELECT r.REGISTRATION_ID, r.DONOR_ID, r.REGISTRATION_STATUS, r.ATTENDANCE_STATUS, 
           d.FULL_NAME, d.NIC, d.BLOOD_GROUP,
           (SELECT COUNT(*) FROM DONATION_RECORD rec WHERE rec.REGISTRATION_ID = r.REGISTRATION_ID) AS HAS_DONATED
    FROM CAMP_REGISTRATION r
    JOIN DONOR d ON r.DONOR_ID = d.DONOR_ID
    WHERE r.CAMP_ID = p_camp_id
    ORDER BY d.FULL_NAME ASC;
END GET_CAMP_ATTENDANCE;
/

CREATE OR REPLACE PROCEDURE RECORD_CAMP_DONATION(
    p_user_id IN NUMBER,
    p_registration_id IN NUMBER,
    p_camp_id IN NUMBER,
    p_donor_id IN NUMBER,
    p_blood_group IN VARCHAR2,
    p_units IN NUMBER
) AS
    v_committee_id NUMBER;
    v_camp_date DATE;
BEGIN
    SELECT COMMITTEE_ID INTO v_committee_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'ORGANIZING_COMMITTEE';
    
    SELECT CAMP_DATE INTO v_camp_date FROM DONATION_CAMP WHERE CAMP_ID = p_camp_id AND COMMITTEE_ID = v_committee_id;
    
    INSERT INTO DONATION_RECORD (REGISTRATION_ID, CAMP_ID, DONOR_ID, DONATION_DATE, BLOOD_GROUP, UNITS_COLLECTED, STATUS, SUBMITTED_AT)
    VALUES (p_registration_id, p_camp_id, p_donor_id, v_camp_date, p_blood_group, p_units, 'SUBMITTED', SYSTIMESTAMP);
    
    UPDATE CAMP_REGISTRATION 
    SET ATTENDANCE_STATUS = 'COMPLETED', CHECK_IN_AT = SYSTIMESTAMP, CHECK_OUT_AT = SYSTIMESTAMP
    WHERE REGISTRATION_ID = p_registration_id;
    
    COMMIT;
END RECORD_CAMP_DONATION;
/

CREATE OR REPLACE PROCEDURE DISPATCH_DONATION_TRANSFER(
    p_user_id IN NUMBER,
    p_camp_id IN NUMBER,
    p_blood_bank_id IN NUMBER,
    p_transfer_id OUT NUMBER,
    p_transfer_code OUT VARCHAR2
) AS
    v_committee_id NUMBER;
    v_count NUMBER;
    
    CURSOR c_untransferred IS
        SELECT DONATION_ID FROM DONATION_RECORD 
        WHERE CAMP_ID = p_camp_id AND STATUS = 'SUBMITTED' 
          AND DONATION_ID NOT IN (SELECT DONATION_ID FROM DONATION_TRANSFER_ITEM);
BEGIN
    SELECT COMMITTEE_ID INTO v_committee_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'ORGANIZING_COMMITTEE';
    
    p_transfer_code := 'TRF-' || p_camp_id || '-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS');
    
    INSERT INTO DONATION_TRANSFER (CAMP_ID, COMMITTEE_ID, BLOOD_BANK_ID, TRANSFER_CODE, STATUS, DISPATCHED_AT)
    VALUES (p_camp_id, v_committee_id, p_blood_bank_id, p_transfer_code, 'DISPATCHED', SYSTIMESTAMP)
    RETURNING TRANSFER_ID INTO p_transfer_id;
    
    v_count := 0;
    FOR rec IN c_untransferred LOOP
        INSERT INTO DONATION_TRANSFER_ITEM (TRANSFER_ID, DONATION_ID, UNITS_TRANSFERRED)
        VALUES (p_transfer_id, rec.DONATION_ID, 1);
        v_count := v_count + 1;
    END LOOP;
    
    IF v_count = 0 THEN
        ROLLBACK;
        p_transfer_id := -1;
        p_transfer_code := 'NO_UNITS_FOUND';
    ELSE
        UPDATE DONATION_CAMP SET STATUS = 'COMPLETED' WHERE CAMP_ID = p_camp_id;
        COMMIT;
    END IF;
END DISPATCH_DONATION_TRANSFER;
/

CREATE OR REPLACE PROCEDURE GET_COMMITTEE_STAFF(
    p_user_id IN NUMBER,
    p_result_cursor OUT SYS_REFCURSOR
) AS
    v_committee_id NUMBER;
BEGIN
    SELECT COMMITTEE_ID INTO v_committee_id FROM USER_ROLE_LINK WHERE USER_ID = p_user_id AND ROLE_CODE = 'ORGANIZING_COMMITTEE';
    
    OPEN p_result_cursor FOR
    SELECT s.STAFF_ID, s.FULL_NAME, s.POSITION_TITLE, s.PHONE, s.EMAIL, a.ASSIGNED_FROM, a.STATUS
    FROM COMMITTEE_STAFF_ASSIGNMENT a
    JOIN STAFF_MEMBER s ON a.STAFF_ID = s.STAFF_ID
    WHERE a.COMMITTEE_ID = v_committee_id;
END GET_COMMITTEE_STAFF;
/
